### ISSUE TITLE
Does not work under jq 1.7 (default in Alpine)

### ISSUE THREAD

**Issue by lawik** [nerves-project/asdf-plugin-nerves-toolchain#13]
**Describe the bug**

Trying to make this work in a Dockerfile with Alpine Linux I got an empty URL passed to curl for an install process that worked on the host.

**Steps to reproduce**

It should reproduce if you install `jq` version 1.7 and try to install a toolchain. It won't be found and curl will choke.

**Expected behavior**

Ideally it should work the same as with jq 1.6.

**dockerfile**

This docker file puppeteers the process without asdf/mise. The original alpine version and alpine installs are still in there commented out to reproduce the bug. This can be run as 

```
docker build --build-arg "GITHUB_API_TOKEN=$(gh auth token)" .
```

```
ARG ELIXIR_VERSION="1.17.1"
ARG OTP_VERSION="26.2.5.1"
ARG GITHUB_API_TOKEN
#FROM hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-alpine-3.20.1
FROM hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-ubuntu-jammy-20240530
ARG GITHUB_API_TOKEN

#RUN apk add --no-cache bash build-base git curl jq mise xz
RUN apt-get update && apt-get install -y bash build-essential git curl jq xz-utils

WORKDIR /build
COPY bin bin
COPY lib lib 
COPY scripts scripts
RUN ./bin/list-all
RUN mkdir /build/download
RUN export ASDF_INSTALL_TYPE="version" && \
    export ASDF_INSTALL_VERSION="v13.2.0-x86_64-nerves-linux-gnu" && \
    export ASDF_INSTALL_PATH="/build/toolchain/" && \
    export ASDF_DOWNLOAD_PATH="/build/download" && \
    ./bin/download
```

**Comment by bjyoungblood** [comment]
@lawik Try out #14 when you get a chance!
